# Arithmetic Exception

Num1=5
Num2=0
result=Num1/Num2
print("Result:",result)